# 运行命令：docker-compose up -d --build

services:
  backend:
    build: backend
    image: case-automl-backend:latest
    ports:
      - "8080:8080"
      - "54321:54321"
    volumes:
      - ./backend:/app/backend
    networks:
      - project_network

  frontend:
    build: frontend
    image: case-automl-frontend:latest
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend
    networks:
      project_network:

networks:
  project_network: